export const ASSETS = {
  serviceLogo: "assets/images/service-logo-cropped.png",
  footerLogo: "assets/images/service-logo-footer-white.png",
  heroPerson: "assets/images/hero-person.png",
  heroMovie: "assets/videos/hero-movie-1.mp4",
  heroBackground: "assets/images/hero-background.png",
  problemIllustration: "assets/images/problem-illustration.png",
  problemOnayami: "assets/images/problem-onayami-t.png",
  campaignBanner: "assets/images/campaign-visual.png",
  guaranteeBanner: "assets/images/guarantee-visual.png",
  aboutMain: "assets/images/coaching-ai-support-2.png",
  aboutAiShien: "assets/images/about-ai-shien.png",
  aboutAiKatsuyo: "assets/images/about-ai-katsuyo.png",
  aboutCoachingAi: "assets/images/about-coaching-ai.png",
  ctaPeople: "assets/images/cta-people-generated.png",
  ctaStep02: "assets/images/cta-step02-t.png",
  featureBackdrop: "assets/images/about-bg.png",
  featureHyakunin: "assets/images/feature-hyakunin-2.png",
  supportIconPeople: "assets/images/support-icon-people.png",
  supportIconChat: "assets/images/support-icon-chat.png",
  profilePhoto: "assets/images/profile-photo.png",
  flowIllustrations: [
    "assets/images/flow-step-01.png",
    "assets/images/flow-step-02.png",
    "assets/images/flow-step-03.png",
  ],
  storyPortraits: [
    "assets/images/story-01.jpg",
    "assets/images/story-02.jpg",
    "assets/images/story-03.jpg",
    "assets/images/instructor-04-generated.png",
    "assets/images/instructor-05-generated.png",
    "assets/images/instructor-06-generated.png",
    "assets/images/instructor-07-generated.png",
  ],
  customerCases: [
    "assets/images/customer-cases/customer-case-01.png",
    "assets/images/customer-cases/customer-case-02.png",
    "assets/images/customer-cases/customer-case-03.jpg",
    "assets/images/customer-cases/customer-case-04.png",
    "assets/images/customer-cases/customer-case-05.jpg",
    "assets/images/customer-cases/customer-case-06.jpg",
    "assets/images/customer-cases/customer-case-07.png",
    "assets/images/customer-cases/customer-case-08.png",
    "assets/images/customer-cases/customer-case-09.png",
    "assets/images/customer-cases/customer-case-10.png",
    "assets/images/customer-cases/customer-case-11.jpg",
    "assets/images/customer-cases/customer-case-12.jpg",
    "assets/images/customer-cases/customer-case-13.png",
    "assets/images/customer-cases/customer-case-14.png",
    "assets/images/customer-cases/customer-case-15.png",
  ],
} as const;
